spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: oreocookie1!

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080