spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/ahmedelsawi
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080